<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1664079984928' stop='1664080023398'>
    <name>Protractor Demo App</name>
    <title>Protractor Demo App</title>
    <test-cases>
        <test-case start='1664079984929' status='passed' stop='1664079999277'>
            <name>should have a title1</name>
            <title>should have a title1</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='bd871683-a8fe-4448-b391-fdd04d9cd36e-attachment.png' type='image/png' size='21207'/>
            </attachments>
        </test-case>
        <test-case start='1664079999277' status='failed' stop='1664080009195'>
            <name>should have a title2</name>
            <title>should have a title2</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='d4ea5580-94aa-4b26-bd6d-27d1fe9c52ce-attachment.png' type='image/png' size='17201'/>
            </attachments>
            <failure>
                <message>Failed: Index out of bound. Trying to access element at index: 2, but there are only 2 elements that match locator by.repeater("result in memory")</message>
                <stack-trace>NoSuchElementError: Index out of bound. Trying to access element at index: 2, but there are only 2 elements that match locator by.repeater("result in memory")
                    at C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\built\element.js:274:27
                    at ManagedPromise.invokeCallback_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
                    at C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
                    at ElementArrayFinder.applyAction_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as getText] (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as getText] (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
                    at UserContext.&lt;anonymous> (D:\synechron_JS\Training\protractor\ChainLocators.js:117:107)
                    at C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                From: Task: Run it("should have a title2") in control flow
                    at UserContext.&lt;anonymous> (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
                    at attempt (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at QueueRunner.execute (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
                    at Spec.execute (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
                    at UserContext.fn (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
                    at attempt (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (D:\synechron_JS\Training\protractor\ChainLocators.js:80:5)
                    at addSpecsToSuite (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (D:\synechron_JS\Training\protractor\ChainLocators.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:1063:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
                    at Module.load (internal/modules/cjs/loader.js:928:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:769:14)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1664080009195' status='passed' stop='1664080023397'>
            <name>should have a title</name>
            <title>should have a title</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='b60bc29f-8703-423f-98a9-039f2846707a-attachment.png' type='image/png' size='21162'/>
            </attachments>
        </test-case>
    </test-cases>
</ns2:test-suite>